apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app
          image: 368707729092.dkr.ecr.us-east-1.amazonaws.com/deepseek-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
